package adapter;

public class TheaterQuotes {
	String[] quotes={"Time flows constantly, it doesn’t care about the people who are struggling.",
			"All those moments will be lost in time… like tears in rain",
			"I'll be back",
			"Of all the gin joints in all the towns in all the world, she walks into mine.\r\n",
			"...Bond. James Bond",
			"Frankly, my dear, I don't give a damn!",
			"Well, it's not the men in your life that counts, it's the life in your men",
			"When will the war end? When someone wins.",
			"My Mama always said, 'Life was like a box of chocolates; you never know what you're gonna get",
			"Dobby is free.",
			"Love means never having to say you're sorry",
			"You're gonna need a bigger boat",
			"May the Force be with you",
			"I'm going to make him an offer he can't refuse",
			"You talkin' to me?",
			"The first rule of Fight Club is: You do not talk about Fight Club",
			"I solemnly swear I am up to no good",
			"I am your father",
			"Hello. My name is Inigo Montoya. You killed my father. Prepare to die",
			"Why so serious?",
			"I'll be back",
			"Yippie-ki-yay, motherf—er!",
			"Houston, we have a problem.",
			"Here's Johnny!",
			"Say hello to my little friend!",
			"You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya punk?",
			"Wait A Minute, Doc. Are You Telling Me You Built A Time Machine...Out Of A DeLorean?",
			"Great Scott!",
			"Numbing the pain for a while will make it worse when you finally feel it.",
			"It does not do to dwell on dreams and forget to live",
			"Keep your friends close, but your enemies closer.",
			"Mama says, 'Stupid is as stupid does.'",//35
			"I'm having an old friend for dinner.",
			"Hasta la vista, baby.",
			"if nobody cares to accept you and wants you in this world, accept yourself and you will see that you don’t need them and their selfish ideas",
			"The ticket to the future is always open.",
			"Life is not a game of luck. If you wanna win, work hard",
			"Power comes in response to a need, not a desire. You have to create that need",
			"If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be",
			"To defeat evil, I shall become an even GREATER evil."};

}
